server:
  port: ${SERVER_PORT:8081}

ai:
  summarizer:
    base-url: http://localhost:5001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/knowvault-db}
    username: ${DB_USER:knowvault-user}
    password: ${DB_PASSWORD:knowvault-pass}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080/realms/${keycloak.admin.realm}}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    baseline-version: 0

  jpa:
    generate-ddl: false

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_URL:http://localhost:8080/}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:KnowVault}
    realm: ${KEYCLOAK_ADMIN_REALM:KnowVault}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:3S0D5f3LGeDhFPrecYXV4wcC15kJKxh9}
    grant-type: ${KEYCLOAK_ADMIN_GRANT_TYPE:client_credentials}
